name: "gbraad's Dotfiles `devenv` Action"
description: 'Wrapper for devenv command execution on GitHub runners'
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  prefix:
    description: 'The container image to use'
    required: true
    default: ''
  command:
    description: 'Command to execute (sys, start, shell, etc.)'
    required: true
    default: 'shell'
  args:
    description: 'Additional arguments for the command'
    required: false
    default: ''
  as_user:
    description: 'User to run the commands as (optional)'
    required: false
    default: ""
outputs:
  prefix:
    description: 'The prefix (container image) that was used'
    value: ${{ inputs.prefix }}
runs:
  using: 'composite'
  steps:
    - name: Execute devenv command
      uses: gbraad-actions/zsh-action@main
      with:
        as_user: ${{ inputs.as_user }}
        run: |
          # Check if devenv function exists
          if ! type devenv >/dev/null 2>&1; then
            echo "Error: devenv function is not defined. Please make sure to run install first"
            exit 1
          fi
          
          # Execute devenv command
          devenv ${{ inputs.prefix }} ${{ inputs.command }} ${{ inputs.args }}
